import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { CSPostHogProvider } from "../components/providers";
import I18nProvider from "@/components/providers/I18nProvider";
import TrayLanguageSync from "@/components/providers/TrayLanguageSync";
import TrayProSync from "@/components/providers/TrayProSync";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CSPostHogProvider>
          <I18nProvider>
            <TrayLanguageSync />
            <TrayProSync />
            {children}
          </I18nProvider>
        </CSPostHogProvider>
      </body>
    </html>
  );
}
